import { normalizeItemName } from './normalizeItemName';

describe('normalizeItemName', () => {
  it('works', () => {
    const itemNames = [
      '秃鹫级',
      '茶隼级',
      '伊毕斯号',
      '探索级隐匿型',
      '富豪级隐匿型',
      '伊米卡斯级',
      '弦月级原型',
      '残月级原型',
      '狐鼬级',
      '茅斯卡特 小型来复磁',
      '火石 中型来复磁轨炮',
      '恶徒 中型短管磁轨炮',
      '科必伊C 小型远程装…',
      '科波姆C 反应式装甲…',
      '科必伊C 小型装甲维…',
      '科波斯C 大型装甲维…',
      '科波斯C 大型远程装…',
      '科波斯C 大型集束激…',
      '科波姆C 中型装甲维…',
      '科波姆C 中型远程装…',
      '科必伊C 小型集束激…',
      '血袭者受损结构',
      '科必伊C 小型脉冲激…',
      '科波姆C 中型脉冲激…',
      'MK7大型集束激光炮',
      '科波斯C 大型集束激…',
      'MK7 中型脉冲激光炮',
      '科波姆C 中型脉冲激…',
      'MK7 中型掠能器',
      '科波姆C 中型远程装…',
      'MK7 无人机导航电脑',
      'MK7 全方位索敌连接',
      'MK7 损伤控制',
      '科波姆C 中型装甲维…',
      '艾玛B级受损结构',
      '商人 小型跃迁推进器',
      'MK5 中型跃迁推进器',
      '圣光 跃迁核心稳定器',
      '基础型 惯性稳定器',
      'MK7 胡蜂',
      '数据核心 一 激光物理',
      '舰载扫描与跃迁指南',
      '空间航行技术理论',
      'MK7 Medium Torpedo...',
      'MK7 Small Energy...',
      'MK7 Medium Energy...',
      'MK5 Covert Ops Cloakin...',
      `'DeaIer' Small...`,
      'MK5 Medium...',
      `'Aura' Warp Core...`,
      'Basic Inertial Stabilizer',
      'MK7 Wasp',
      'Datacore - Laser...',
      'Shipboard Scanning and',
      'Interstellar Navigation...',
      'Condor',
      'Kestrel',
      'Ibis',
      'Probe Covert Ops',
      'Magnate Covert Ops',
      'Imicus',
      'Xian-Yue Prototype',
      'Can-Yue Prototype',
      'Tayra',
      `'Musket' Small Rifled...`,
      `'FIintIock' Medium Rifle`,
      `'HustIer' Medium...`,
      'Slasher II',
      'Imious',
      'Warhead Calefaction...',
      'MK7 Warden',
      'Lv. 3 Pilot Medal',
      'Ancient Remains',
      'New Eden Source',
      'Ancient Treasure Map',
      'Vial of Mikramurka',
      'Magic Crystal Ball',
      'Dice of Jade',
      'Ancient Painblade',
      `Kri'tak Knife`,
      'Raata Wind Chimes',
      'Nursery Rhyme',
      'Onyx Heart of Valor',
    ];
    const actual = itemNames.map(normalizeItemName);

    const expected = [
      { type: 'ExactMatch', text: '秃鹫级' },
      { type: 'ExactMatch', text: '茶隼级' },
      { type: 'ExactMatch', text: '伊毕斯号' },
      { type: 'ExactMatch', text: '探索级隐匿型' },
      { type: 'ExactMatch', text: '富豪级隐匿型' },
      { type: 'ExactMatch', text: '伊米卡斯级' },
      { type: 'ExactMatch', text: '弦月级原型' },
      { type: 'ExactMatch', text: '残月级原型' },
      { type: 'ExactMatch', text: '狐鼬级' },
      { type: 'ExactMatch', text: '茅斯卡特 小型来复磁轨炮' },
      { type: 'ExactMatch', text: '火石 中型来复磁轨炮' },
      { type: 'ExactMatch', text: '恶徒 中型短管磁轨炮' },
      { type: 'ExactMatch', text: '科必伊C 小型远程装甲维修器' },
      { type: 'ExactMatch', text: '科波姆C 反应式装甲增强器' },
      { type: 'ExactMatch', text: '科必伊C 小型装甲维修器' },
      { type: 'ExactMatch', text: '科波斯C 大型装甲维修器' },
      { type: 'ExactMatch', text: '科波斯C 大型远程装甲维修器' },
      { type: 'ExactMatch', text: '科波斯C 大型集束激光炮' },
      { type: 'ExactMatch', text: '科波姆C 中型装甲维修器' },
      { type: 'ExactMatch', text: '科波姆C 中型远程装甲维修器' },
      { type: 'ExactMatch', text: '科必伊C 小型集束激光炮' },
      { type: 'ExactMatch', text: '血袭者受损结构' },
      { type: 'ExactMatch', text: '科必伊C 小型脉冲激光炮' },
      { type: 'ExactMatch', text: '科波姆C 中型脉冲激光炮' },
      { type: 'ExactMatch', text: 'MK7 大型集束激光炮' },
      { type: 'ExactMatch', text: '科波斯C 大型集束激光炮' },
      { type: 'ExactMatch', text: 'MK7 中型脉冲激光炮' },
      { type: 'ExactMatch', text: '科波姆C 中型脉冲激光炮' },
      { type: 'ExactMatch', text: 'MK7 中型掠能器' },
      { type: 'ExactMatch', text: '科波姆C 中型远程装甲维修器' },
      { type: 'ExactMatch', text: 'MK7 无人机导航电脑' },
      { type: 'ExactMatch', text: 'MK7 全方位索敌连接' },
      { type: 'ExactMatch', text: 'MK7 损伤控制' },
      { type: 'ExactMatch', text: '科波姆C 中型装甲维修器' },
      { type: 'ExactMatch', text: '艾玛8级受损结构' },
      { type: 'ExactMatch', text: '商人 小型跃迁推进器' },
      { type: 'ExactMatch', text: 'MK5 中型跃迁推进器' },
      { type: 'ExactMatch', text: '圣光 跃迁核心稳定器' },
      { type: 'ExactMatch', text: '基础型 惯性稳定器' },
      { type: 'ExactMatch', text: 'MK7 胡蜂' },
      { type: 'ExactMatch', text: '数据核心 - 激光物理' },
      { type: 'ExactMatch', text: '舰载扫描与跃迁指南' },
      { type: 'ExactMatch', text: '空间航行技术理论' },
      { type: 'ExactMatch', text: 'MK7 Medium Torpedo Launcher' },
      { type: 'NormalizationOnly', normalizedText: 'MK7 Small Energy' },
      { type: 'NormalizationOnly', normalizedText: 'MK7 Medium Energy' },
      { type: 'NormalizationOnly', normalizedText: 'MK5 Covert Ops Cloakin' },
      { type: 'NormalizationOnly', normalizedText: "'Dealer' Small" },
      { type: 'NormalizationOnly', normalizedText: 'MK5 Medium' },
      { type: 'ExactMatch', text: "'Aura' Warp Core Stabilizer" },
      { type: 'ExactMatch', text: 'Basic Inertial Stabilizer' },
      { type: 'ExactMatch', text: 'MK7 Wasp' },
      { type: 'ExactMatch', text: 'Datacore - Laser Physics' },
      { type: 'ExactMatch', text: 'Shipboard Scanning and Warping Guide' },
      { type: 'ExactMatch', text: 'Interstellar Navigation Technology' },
      { type: 'ExactMatch', text: 'Condor' },
      { type: 'ExactMatch', text: 'Kestrel' },
      { type: 'ExactMatch', text: 'Ibis' },
      { type: 'ExactMatch', text: 'Probe Covert Ops' },
      { type: 'ExactMatch', text: 'Magnate Covert Ops' },
      { type: 'ExactMatch', text: 'Imicus' },
      { type: 'ExactMatch', text: 'Xian-Yue Prototype' },
      { type: 'ExactMatch', text: 'Can-Yue Prototype' },
      { type: 'ExactMatch', text: 'Tayra' },
      { type: 'ExactMatch', text: "'Musket' Small Rifled Railgun" },
      { type: 'ExactMatch', text: "'Flintlock' Medium Rifled Railgun" },
      { type: 'NormalizationOnly', normalizedText: "'Hustler' Medium" },
      { type: 'ExactMatch', text: 'Slasher II' },
      { type: 'ExactMatch', text: 'Imicus' },
      { type: 'NormalizationOnly', normalizedText: 'Warhead Calefaction' },
      { type: 'ExactMatch', text: 'MK7 Warden' },
      { type: 'ExactMatch', text: 'Lv. 3 Pilot Medal' },
      { type: 'ExactMatch', text: 'Ancient Remains' },
      { type: 'ExactMatch', text: 'New Eden Source' },
      { type: 'ExactMatch', text: 'Ancient Treasure Map' },
      { type: 'ExactMatch', text: 'Vial of Mikramurka' },
      { type: 'ExactMatch', text: 'Magic Crystal Ball' },
      { type: 'ExactMatch', text: 'Dice of Jade' },
      { type: 'ExactMatch', text: 'Ancient Painblade' },
      { type: 'ExactMatch', text: "Kri'tak Knife" },
      { type: 'ExactMatch', text: 'Raata Wind Chimes' },
      { type: 'ExactMatch', text: 'Nursery Rhyme' },
      { type: 'ExactMatch', text: 'Onyx Heart of Valor' },
    ] as const;
    expect(actual).toEqual(expected);
  });
});
